### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by Arc676** [comment]
This commit somehow seems to be empty...

**Comment by Vistaus** [comment]
Wtf? GitHub deleted or skipped the file somehow. Will try again…

**Comment by Vistaus** [comment]
Should be there now, except that GitHub now referenced another PR in the commit description. Not sure what's happening here lol.

**Review by Arc676 — APPROVED** [review]
Great! Thank you for your contribution.

Not sure what happened earlier lol.

**Pull request merged**
